### ISSUE TITLE
Use subfields or specializations as values for project_genre

### ISSUE THREAD

**Issue by chrisdaaz** [lib-static/lib-static.github.io#10]
To make the [Models page](https://lib-static.onrender.com/models/) easier to browse, I think the `project_genre` field should be controlled around familiar subfields or specializations within GLAM, like these maybe:

- Digital Collections (CollectionBuilder)
- Publishing (Quire)
- Digital Humanities (CTRL+Shift)
- Open Educational Resources (DHLG)
- Utility (pagemaster)

Any others?

**Comment by evanwill** [comment]
i think we did this
