### ISSUE TITLE
Liquid syntax in code blocks break concepts.html

### ISSUE THREAD

**Issue by chrisdaaz** [lib-static/lib-static.github.io#5]
The code blocks in [`_concepts/templates.md`](https://github.com/lib-static/lib-static.github.io/blob/new_site/_concepts/templates.md) are breaking the concepts page on the [new site](https://lib-static.onrender.com/concepts.html) because they use the `{{ content }}` variable. Will the page continue to be build this way? If so, I can try to fix `_concepts/templates.md` by adding `{% raw %}` tags.

**Comment by dcnb** [comment]
I fixed it while doing some other clean up. No worries. 

I also started perusing this --> https://chrisdaaz.github.io/static-web-scholcomm/

Wow, Chris. That's quite good -- and I wonder if we might borrow/steal or rehash some for the concepts. Markdown, for instance ...
